spring:
  application:
    name: digitalcommerce

data:
  mongodb:
    host: localhost
    port: 27017
    database: digital-commerce
  redis:
    host: localhost
    port: 6379
    password: sa

  cache:
    redis:
      time-to-live: 60000

digital:
  client:
    platzi: https://api.escuelajs.co/api/v1